### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by aaronovz1** [01org/meta-intel-camera#2]
What kernel version does this layer support? Is it 4.4? Are there plans to support the kernel from https://github.com/intel/linux-intel-lts ?

**Comment by friissoren** [comment]
Yes, kernel version 4.4.
Unfortunately all HW and SW development for Joule was discontinued some time ago. There are no plans to update this anymore.

**Comment by aaronovz1** [comment]
Is this repository only for Joule or does it support Apollo Lake? Just curious if we could upgrade from 4.1 kernel we use for APL to 4.4 from this repo while we wait for MR4 BSP with newer kernel.

**Comment by friissoren** [comment]
I cannot guarantee that it will work. Particularly the IPU firmware might be problematic since it is signed and the signing keys aren't necessarily the same on Broxton and Apollo Lake.

**Comment by jbolduc01** [comment]
Is Apollo Lake support would be active by now? In 2020?
